### ISSUE TITLE
OES_texture_float extension not supported

### ISSUE THREAD

**Issue by NHQ** [mikolalysenko/oregon-synth#1]
```check.js:21 Error: (regl) "OES_texture_float" extension is not supported by the current WebGL context, try upgrading your system or a different browser
    at checkConstructor.raise (http://localhost:9966/index.js:21436:15)
    at Object.onDone (http://localhost:9966/index.js:22565:13)
    at createExtensionCache (http://localhost:9966/index.js:18006:14)
    at wrapREGL (http://localhost:9966/index.js:22714:24)
    at Object.2../gfx (http://localhost:9966/index.js:155:27)
    at s (http://localhost:9966/index.js:1:254)
    at e (http://localhost:9966/index.js:1:425)
    at http://localhost:9966/index.js:1:443

```
```

**Comment by NHQ** [comment]
i tried enabling with chrome flags but still not supported, this must be something with the chromium build on this odroid

**Comment by mikolalysenko** [comment]
Unfortunately the example needs OES_texture_float for filtering the audio.  I could try hacking it to use a lower precision, but it would cause artefacts in the audio synthesis.
